name: Fluid Data Processing and Commit

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  process_fluid_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Debug Repository Structure
        run: ls -R "$GITHUB_WORKSPACE"

      - name: Verify CLI Module Exists
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/src/json_to_vtk/cli.py" ]; then
            echo "❌ Error: cli.py not found inside src/json_to_vtk/!"
            exit 1
          fi

      - name: Clean Previous Output
        run: |
          TARGET="$GITHUB_WORKSPACE/data/testing-input-output"
          if [ -d "$TARGET" ]; then
            rm -rf "$TARGET"/*
            echo "🧹 Cleaned existing files in $TARGET"
          fi

      - name: Make download_from_dropbox.sh Executable
        run: chmod +x src/download_from_dropbox.sh

      - name: Download Simulation Files from Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: src/download_from_dropbox.sh

      - name: Run JSON to VTK Conversion via CLI
        run: |
          PYTHONPATH=src \
          python -m json_to_vtk.cli \
            --mesh data/testing-input-output/fluid_mesh_data.json \
            --volume data/testing-input-output/fluid_volume_data.json \
            --outdir data/testing-input-output/vtk_output \
            --write-pvd

      - name: Run tests
        run: PYTHONPATH=src pytest tests/ --verbose

      # - name: Commit and Push Generated VTK Output to Repository
      #   env:
      #     GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      #     GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      #   run: |
      #     git config --global user.name "${GIT_USER_NAME}"
      #     git config --global user.email "${GIT_USER_EMAIL}"
      #     cd "$GITHUB_WORKSPACE"
      #     OUTPUT_DIR="data/testing-input-output/vtk_output"
      #     if [ -d "$OUTPUT_DIR" ] && [ -n "$(ls -A $OUTPUT_DIR)" ]; then
      #       git add "$OUTPUT_DIR"
      #       git status
      #       if [[ $(git diff --cached --quiet; echo $?) -ne 0 ]]; then
      #         git commit -m "Auto-update: Converted fluid data to VTK format"
      #         git push origin HEAD
      #       else
      #         echo "✅ No new changes to commit!"
      #       fi
      #     else
      #       echo "❌ No VTK output files found to commit."

      - name: Make upload_to_dropbox.sh Executable
        run: chmod +x src/upload_to_dropbox.sh

      - name: Debug Before Dropbox Upload
        run: ls -R "$GITHUB_WORKSPACE"

      - name: Upload Fluid Simulation Output to Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: src/upload_to_dropbox.sh



