name: Fluid Data Processing and Commit

on:
  push:
    branches:
      - "**"  # Triggers on any branch
  workflow_dispatch:

jobs:
  process_fluid_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Debug Repository Structure
        run: ls -R $GITHUB_WORKSPACE

      - name: Verify Script Exists
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/generate_blender_format.py" ]; then
            echo "❌ Error: generate_blender_format.py not found!"
            exit 1
          fi

      - name: Run script to process fluid data
        run: python $GITHUB_WORKSPACE/generate_blender_format.py

      - name: Commit and Push Blender Fluid Parameters to Repository
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

          cd $GITHUB_WORKSPACE

          if ls testing-input-output/blender_fluid_parameters.json 1> /dev/null 2>&1; then
            git add testing-input-output/blender_fluid_parameters.json
            git status
            
            if git diff --cached --quiet; then
              echo "✅ No changes to commit!"
            else
              git commit -m "Auto-update: Added latest Blender fluid parameters"
              git push origin HEAD
            fi
          else
            echo "❌ No Blender fluid parameters file detected, skipping commit."
          fi
